### ISSUE TITLE
Not supporting ASA_GM1 products

### ISSUE THREAD

**Issue by Ciyel-real** [avalentino/pyepr#13]
Hello, 

I am currently working on Envisat product types 'ASA_IMM', 'ASA_WSM', 'ASA_APM' and 'ASA_GM1'. This module works perfectly for the first three and I thank you a lot for this but it won't open the ASA_GM1 products.

This is what I have as error:

`
unable to open "ASA_GM1_1PNDSI20060918_155919_000001572051_00197_23798_0000.N1"
Traceback (most recent call last):
  File "process_patch.py", line 325, in <module>
    main()
  File "process_patch.py", line 282, in main
    product_lon_lat=get_lon_lat_array(N1_filepath)
  File "process_patch.py", line 101, in get_lon_lat_array
    file=epr.Product(file)
  File "src/epr.pyx", line 2275, in epr.Product.__cinit__
ValueError: unable to open "ASA_GM1_1PNDSI20060918_155919_000001572051_00197_23798_0000.N1"
`

**Comment by avalentino** [comment]
Dear @Ciyel-real, 
PyEPR is just a Python wrapper for the [C-EPR-API](https://github.com/bcdev/epr-api) so if the the product is supported by the C library it should also be supported by the Python one.

According to what I see in [epr_dddb.c](https://github.com/avalentino/epr-api/blob/2ef75e2b70ff01c7ac26865750608ba652494bb2/src/epr_dddb.c#L3046) It seems to me that ASA_GM1 products should be supported.

Could you please provide a public link to one of the product that you are not able to open?
I would need to make some local test.
