### ISSUE TITLE
"pip install pyepr" on the windows10 python3.8 pyepr1.1.5, this is a error 

### ISSUE THREAD

**Issue by LooperzZ** [avalentino/pyepr#14]
Traceback (most recent call last):
  File "D:\Python_code\sea_ice_drift-master\MODIS_convert.py", line 10, in <module>
    product = epr.Product(file_name)
  File "src\epr.pyx", line 2273, in epr.Product.__cinit__
  File "src\epr.pyx", line 262, in epr.pyepr_check_errors
epr.EPRValueError: ('epr_open_product: invalid product identifier', 203)

**Comment by avalentino** [comment]
Sorry I do not have a Windows machine to reproduce.
For sure it is not a problem with the product, your example works for me (on linux):

```python
>>> import epr
>>> file_name = './ASA_WSM_1PNDSI20120309_155143_000003363112_00270_52439_0000.N1'
>>> product = epr.Product(file_name)
>>> datasets = product.datasets()
>>> print(datasets)

[epr.Dataset(MDS1_SQ_ADS) 6 records,
 epr.Dataset(MAIN_PROCESSING_PARAMS_ADS) 6 records,
 epr.Dataset(DOP_CENTROID_COEFFS_ADS) 55 records,
 epr.Dataset(SR_GR_ADS) 55 records,
 epr.Dataset(CHIRP_PARAMS_ADS) 340 records,
 epr.Dataset(GEOLOCATION_GRID_ADS) 55 records,
 epr.Dataset(MDS1) 29700 records]
```

Could you please provide more info?

**Comment by avalentino** [comment]
Just triggered a new CI build and, apparently, all works fine in Windows with Python 3.8:
https://github.com/avalentino/pyepr/actions/runs/9490846455/job/26155144169

**Comment by avalentino** [comment]
@LooperzZ do you have the chance to build pyepr from sources?

**Comment by avalentino** [comment]
Python 3.8 will no longer be supported starting form the next release.
Please feel free to re-open the issue if you experiment the same problem also with newer Python versions.
